---
title: "data_synthethic"
output: html_document
---

```{r}
library("bnlearn")
library("Rgraphviz")
```


```{r}
network <- read.net('~/Desktop/sadegh3.net')
```

```{r}
graphviz.plot(network)
```

```{r}

add_arg = function(network, first.node, sec.node){
  network.string = modelstring(network)
network.model = model2network(network.string)
all_cpt =c()
  for (i in names(network)){
    all_cpt = c(all_cpt, list(network[[i]]$prob))
  }
  names(all_cpt) = names(network)
  ch_cpt = all_cpt[[sec.node]]
  name_cpt = dimnames(all_cpt[[sec.node]])
  fr_dim = dim(all_cpt[[sec.node]])
  
  dim(ch_cpt) = prod(fr_dim)
  ch_cpt = c(rep(c(0,1,0,1),prod(fr_dim)/4), ch_cpt)
  dim(ch_cpt) = c(fr_dim, 2)
  name.name.cpt = names(name_cpt)
  name_cpt_new =  name_cpt
  name_cpt_new[[first.node]] = c("yes", "no")
  dimnames(ch_cpt) = name_cpt_new 
  all_cpt[[sec.node]] = ch_cpt 


  network.model = set.arc(network.model, from = first.node, to = sec.node)
  network.cpt = custom.fit(x = network.model, dist = all_cpt)

}

```
```{r}
network.new = add_arg(network = network , first.node = 'C',sec.node = 'E')
```
```{r}
graphviz.plot(network.new)
```



```{r}
network2 = network.new
observed.node= c()
check.node = c()
for (i in network2)
  {
    parents.i = i[["parents"]] 
  
    evi = ''
    for (j in check.node)
      {
        if(j %in% observed.node)
          {
            evi = paste(evi, '(', j, "== 'yes' ) &")
          }
        else
          {
            evi = paste(evi,'(',j,"== 'no' ) &")
          }
    }
    evi = substr(evi, 1, nchar(evi) - 1)
    myevent <- paste('(',i[['node']],"== 'yes')" )
    print(evi)
    print(myevent)
    if(evi == '') 
    { 
      
      prob = cpquery(fitted = network2, event = eval(parse(text = myevent)), evidence= TRUE)}
    else
    {
        prob = cpquery(fitted = network2, event = eval(parse(text=myevent)), evidence= eval(parse(text=evi)))}

    print(i[['node']])
    print(prob)
    if(sample(c(0,1), 1, replace = TRUE,c(1-prob,prob)))
      {
        observed.node = c(observed.node, i[['node']])
     
      }
    check.node = c(check.node, i[['node']])

}
observed.node

```



```{r}
network.string = modelstring(network)
mystr=''
myvec =strsplit(network.string, split = ']')[[1]]
not_obs =c()
for(l in myvec)
{
  
  if (substr(l,2,2) %in% observed.node)
  {
    mystr = paste(mystr,l,']', sep="")
  }
  else not_obs = c(not_obs, substr(l,2,2))
}
library("stringr")
for (j in not_obs)
{
  mystr = str_remove_all(mystr, paste(j,':',sep = ''))
  mystr = str_remove_all(mystr, paste(':', j,sep = ''))
  
}
network.new =  model2network(mystr)
graphviz.plot(network.new)

```
```{r}

binary<-function(p_number) {
 
  bin = c()
  while (p_number > 0) {
    digit<-p_number %% 2
    bin <- c(digit,bin)
    p_number<-floor(p_number / 2)
    
  }
  return(bin)
}
```
```{r}
k = network.new
for(i in substr(strsplit(mystr, split = "]")[[1]], 2, 2))
  {
    par = k[['nodes']][[i]][['parents']]
    if(length(par) > 1){
    print(par)

    mysub = subset(par, as.logical(binary(sample(x = c(0: (2^length(par)-2)), size = 1, replace = TRUE))))
    print( mysub)
    for (j in mysub){
      
      k = drop.arc(k, from = j, to = i)
    }
    }
}
graphviz.plot(k)
```

```{r}
active.list =c()
visit.list = c()
for(i in substr(strsplit(mystr, split = "]")[[1]], 2, 2))
  {
    par = k[['nodes']][[i]][['parents']]
    if(length(par) == 0)
       active.list =c(active.list, i)
}
while (!all(substr(strsplit(mystr, split = "]")[[1]], 2, 2) %in% visit.list)) {
  sam = sample(active.list, size = 1)
  visit.list = c(visit.list, sam)
  active.list = active.list[! active.list %in% c(sam)]
  active.list = c(active.list, k[['nodes']][[sam]][['children']])
}
visit.list
```
