---
title: "Colon Synthesizer"
output: html_notebook
---

```{r}
library("bnlearn")
library("Rgraphviz")
library("datastructures")
library('partitions')
```

```{r}
RATE <- 5
TIMELIMIT <- 1
```


```{r}
network <- read.net('sample2.net')
```

```{r}
graphviz.plot(network)
```

```{r}
add_arg = function(network, first.node, sec.node) {
  network.string = modelstring(network)
  network.model = model2network(network.string)
  all_cpt =c()
  for (i in names(network)) {
      all_cpt = c(all_cpt, list(network[[i]]$prob))
  }
  names(all_cpt) = names(network)
  ch_cpt = all_cpt[[sec.node]]
  name_cpt = dimnames(all_cpt[[sec.node]])
  fr_dim = dim(all_cpt[[sec.node]])
  
  dim(ch_cpt) = prod(fr_dim)
  ch_cpt = c(rep(c(0,1,0,1),prod(fr_dim)/4), ch_cpt)
  dim(ch_cpt) = c(fr_dim, 2)
  name.name.cpt = names(name_cpt)
  name_cpt_new =  name_cpt
  name_cpt_new[[first.node]] = c("yes", "no")
  dimnames(ch_cpt) = name_cpt_new 
  all_cpt[[sec.node]] = ch_cpt 

  network.model = set.arc(network.model, from = first.node, to = sec.node)
  network.cpt = custom.fit(x = network.model, dist = all_cpt)
}
```

```{r}
network <- add_arg(network = network , first.node = 'D', sec.node = 'E')
```

```{r}
graphviz.plot(network)
```

```{r}
evidenceToString <- function(observed=NULL, notObserved=NULL) {
    evidenceString = ''
    for (i in observed) {
        evidenceString = paste(evidenceString, '(', i, "== 'yes') &")
    }
    for (i in notObserved) {
        evidenceString = paste(evidenceString, '(', i, "== 'no') &")
    }
    evidenceString <- sub(' &$', '', evidenceString)
}
```

```{r}
randomPartition <- function(n) {
    nParts <- parts(n)
    randPart <- nParts[, sample(ncol(nParts), 1)]
    randPart <- randPart[randPart != 0]
}
```


```{r}
synthesizeColon <- function(network) {
    q <- list()
    colons <- c()
    times <- list()
    roots <- root.nodes(network)
    for (i in 1:length(roots)) {
        ev <<- parse(text=sprintf("%s == 'yes'", roots[i]))
        p <- cpquery(fitted=network, event=eval(ev), evidence=TRUE)
        if (rbinom(1, 1, p) == 1) {
            q <- c(q, roots[i])
            colons <- c(colons, roots[i])
            times[[roots[i]]] <- rexp(1, RATE)
            print(sprintf("%s added", roots[i]))
        }
    }
    
    while (length(q) > 0) {
        colonStr <- q[[1]]
        q <- q[-1]
        # print('popped')
        # print(colon)
        colon <- as.vector(unlist(strsplit(colonStr, split=' ')))
        u <- colon[length(colon)]
        # print(u)
        colonTime <- times[[colonStr]]
        
        allChildren <- c()
        for(u in 1:length(colon)){
            allChildren <- c(allChildren, children(network, colon[u]))
        }
        allChildren <- unique(allChildren)
        allChildren <- allChildren[!(allChildren %in% colon)]
        parents <- colon[!(colon %in% allChildren)]
        
        uChildren <- c()
        # print(evidenceToString(parents, NULL))
        evi <<- parse(text=evidenceToString(parents, NULL))
        if (length(allChildren > 0)) {
            for (i in 1:length(allChildren)) {
                ev <<- parse(text=evidenceToString(allChildren[i]))
                p <- cpquery(network, event=eval(ev), evidence=eval(evi))
                print(evi)
                if (rbinom(1, 1, p) == 1) {
                    uChildren <- c(uChildren, allChildren[i])
                    print(sprintf("%s occured in colon %s with p=%f", allChildren[i], colonStr, p))
                } else {
                    print(sprintf("%s did not occur in colon %s with p=%f", allChildren[i], colonStr, p))
                }
            }
        }
        
        if (length(uChildren) > 0) {
            part <- randomPartition(length(uChildren))
            perm <- sample(uChildren, length(uChildren), replace=FALSE)
            index <- 1
            for (i in 1:length(part)) {
                childrenSet <- perm[index:(index+part[i]-1)]
                childrenSet <- sample(childrenSet, length(childrenSet), replace=FALSE)
                childrenSet <- paste(childrenSet, collapse=' ')
                childrenSet <- paste(colonStr, childrenSet)
                # print('pushed')
                # print(childrenSet)
                childrenTime <- colonTime + rexp(1, RATE)
                if (childrenTime < TIMELIMIT) {
                    colons <- c(colons, childrenSet)
                    q <- c(q, childrenSet)
                    times[[childrenSet]] <- childrenTime
                    index <- index + part[i]
                    print(sprintf("For colon %s, time = %f", childrenSet, childrenTime))
                } else {
                    print(sprintf("Time limit reached for colon %s, time = %f", childrenSet, childrenTime))
                }
            }
        }
    }
    colons
}
```

```{r}
synthesizeColon(network)
```


```{r}
network2 = network.new
observed.node= c()
check.node = c()
for (i in network2) {
    parents.i = i[["parents"]] 
    evi = ''
    for (j in check.node) {
        if(j %in% observed.node) {
            evi = paste(evi, '(', j, "== 'yes' ) &")
        } else {
            evi = paste(evi,'(',j,"== 'no' ) &")
        }
    }
    evi = substr(evi, 1, nchar(evi) - 1)
    myevent <- paste('(',i[['node']],"== 'yes')" )
    print(evi)
    print(myevent)
    if(evi == '') { 
        prob = cpquery(fitted = network2, event = eval(parse(text = myevent)), evidence= TRUE)}
    else {
        prob = cpquery(fitted = network2, event = eval(parse(text=myevent)), evidence= eval(parse(text=evi)))
    }
    print(i[['node']])
    print(prob)
    if(sample(c(0,1), 1, replace = TRUE,c(1-prob,prob))) {
        observed.node = c(observed.node, i[['node']])
    }
    check.node = c(check.node, i[['node']])
}
observed.node
```

```{r}
network.string = modelstring(network)
mystr = ''
myvec = strsplit(network.string, split = ']')[[1]]
not_obs = c()

for (l in myvec) {
  if (substr(l,2,2) %in% observed.node) {
    mystr = paste(mystr,l,']', sep="")
  }
  else not_obs = c(not_obs, substr(l,2,2))
}
library("stringr")
for (j in not_obs)
{
  mystr = str_remove_all(mystr, paste(j,':',sep = ''))
  mystr = str_remove_all(mystr, paste(':', j,sep = ''))
  
}
network.new =  model2network(mystr)
graphviz.plot(network.new)

```

```{r}
binary <- function(p_number) {
  bin = c()
  while (p_number > 0) {
    digit<-p_number %% 2
    bin <- c(digit,bin)
    p_number<-floor(p_number / 2)
  }
  return(bin)
}
```

```{r}
k = network.new
for(i in substr(strsplit(mystr, split = "]")[[1]], 2, 2))
  {
    par = k[['nodes']][[i]][['parents']]
    if(length(par) > 1){
    print(par)

    mysub = subset(par, as.logical(binary(sample(x = c(0: (2^length(par)-2)), size = 1, replace = TRUE))))
    print( mysub)
    for (j in mysub){
      
      k = drop.arc(k, from = j, to = i)
    }
    }
}
graphviz.plot(k)
```

```{r}
active.list =c()
visit.list = c()
for(i in substr(strsplit(mystr, split = "]")[[1]], 2, 2))
  {
    par = k[['nodes']][[i]][['parents']]
    if(length(par) == 0)
       active.list =c(active.list, i)
}
while (!all(substr(strsplit(mystr, split = "]")[[1]], 2, 2) %in% visit.list)) {
  sam = sample(active.list, size = 1)
  visit.list = c(visit.list, sam)
  active.list = active.list[! active.list %in% c(sam)]
  active.list = c(active.list, k[['nodes']][[sam]][['children']])
}
visit.list
```
